const categories = [
  'Select Category',
  'Technology and Software',
  'Engineering and Electronics',
  'Health and Wellness',
  'Education and E-Learning',
  'Arts and Entertainment',
  'Social and Networking',
  'Travel and Exploration',
  'E-Commerce and Retail',
  'Finance and Fintech',
  'Sustainability and Green Tech',
  'Food and Beverage',
  'Automotive and Transportation',
  'Real Estate and Property',
  'Charity and Non-Profit',
  'Government and Civic Tech',
  'Fashion and Apparel',
  'Sports and Recreation',
  'Manufacturing and Industrial',
  'Agriculture and Farming',
  'Media and Publishing',
  'Other',
];

export const communityCategories = [
  'Academic and Study Support',
  'Career and Professional Development',
  'Technology and Innovation',
  'Arts and Creativity',
  'Hobbies and Interests',
  'Wellness and Lifestyle',
  'Community Service and Volunteering',
  'Cultural and Language Exchange',
  'Networking and Socializing',
  'Fun and Entertainment',
  'Special Interest Groups',
  'Other',
];

export default categories;
